# Generated by Django 5.0.2 on 2024-03-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_register_remove_feedback_id_alter_feedback_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=20)),
                ('comments', models.TextField()),
            ],
            options={
                'db_table': 'FeedBackList',
            },
        ),
    ]
